USE campus_it;
INSERT INTO application (nom) VALUES
  ('Portail Étudiant'),
  ('Gestion Absences'),
  ('Intranet'),
  ('Helpdesk'),
  ('Parc Informatique');
INSERT INTO ressource (nom, unite) VALUES
  ('Stockage', 'Go'),
  ('CPU', 'vCPU'),
  ('Réseau', 'Go');
INSERT INTO consommation (app_id, res_id, mois, volume) VALUES
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-01-01', 131.05),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-01-01', 11.22),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-01-01', 159.5),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-01-01', 81.11),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-01-01', 7.44),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-01-01', 69.31),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-01-01', 72.7),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-01-01', 6.57),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-01-01', 93.68),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-01-01', 42.12),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-01-01', 13.49),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-01-01', 58.71),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-01-01', 117.99),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-01-01', 9.37),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-01-01', 70.04),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-02-01', 136.41),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-02-01', 11.98),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-02-01', 160.48),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-02-01', 85.19),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-02-01', 8.63),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-02-01', 72.7),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-02-01', 80.1),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-02-01', 7.48),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-02-01', 105.42),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-02-01', 46.19),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-02-01', 14.41),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-02-01', 58.4),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-02-01', 131.83),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-02-01', 10.05),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-02-01', 75.77),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-03-01', 131.01),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-03-01', 12.33),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-03-01', 173.81),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-03-01', 89.97),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-03-01', 9.22),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-03-01', 69.71),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-03-01', 75.23),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-03-01', 7.88),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-03-01', 103.55),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-03-01', 50.72),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-03-01', 13.67),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-03-01', 58.87),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-03-01', 140.44),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-03-01', 10.72),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-03-01', 83.03),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-04-01', 146.8),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-04-01', 12.1),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-04-01', 178.18),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-04-01', 93.78),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-04-01', 9.03),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-04-01', 74.37),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-04-01', 82.21),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-04-01', 7.46),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-04-01', 104.19),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-04-01', 49.73),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-04-01', 13.5),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-04-01', 58.1),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-04-01', 133.03),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-04-01', 10.69),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-04-01', 82.41),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-05-01', 146.42),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-05-01', 11.73),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-05-01', 170.54),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-05-01', 95.37),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-05-01', 8.37),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-05-01', 70.05),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-05-01', 81.79),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-05-01', 7.84),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-05-01', 109.12),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-05-01', 49.8),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-05-01', 14.45),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-05-01', 60.55),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-05-01', 135.33),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-05-01', 10.76),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-05-01', 79.61),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-06-01', 148.72),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-06-01', 12.44),
  ((SELECT app_id FROM application WHERE nom='Portail Étudiant'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-06-01', 182.68),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-06-01', 98.58),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-06-01', 8.67),
  ((SELECT app_id FROM application WHERE nom='Gestion Absences'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-06-01', 70.42),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-06-01', 77.3),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-06-01', 7.85),
  ((SELECT app_id FROM application WHERE nom='Intranet'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-06-01', 108.45),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-06-01', 52.74),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-06-01', 14.19),
  ((SELECT app_id FROM application WHERE nom='Helpdesk'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-06-01', 57.9),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='Stockage'), '2025-06-01', 142.89),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='CPU'), '2025-06-01', 10.82),
  ((SELECT app_id FROM application WHERE nom='Parc Informatique'), (SELECT res_id FROM ressource WHERE nom='Réseau'), '2025-06-01', 80.51);
